#!/usr/bin/env python
# Copyright (c) OpenMMLab. All rights reserved.
"""Create a customized RF-DETR COCO config from a template."""
import argparse
import os
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description='Create an RF-DETR config for a COCO-format dataset.')
    parser.add_argument(
        '--template', default='configs/rfdetr/rfdetr_base_r50_8xb4-12e_coco.py')
    parser.add_argument('--output', required=True)
    parser.add_argument('--data-root', required=True)
    parser.add_argument('--num-classes', required=True, type=int)
    parser.add_argument('--train-ann', default='annotations/instances_train2017.json')
    parser.add_argument('--val-ann', default='annotations/instances_val2017.json')
    parser.add_argument('--train-prefix', default='train2017/')
    parser.add_argument('--val-prefix', default='val2017/')
    return parser.parse_args()


def main():
    args = parse_args()
    template = Path(args.template)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    base_path = os.path.relpath(template, output.parent)
    config_text = f'''# Generated by tools/rfdetr/create_coco_config.py
_base_ = {base_path!r}

model = dict(bbox_head=dict(num_classes={args.num_classes}))
data_root = {args.data_root!r}
train_dataloader = dict(dataset=dict(
    data_root=data_root,
    ann_file={args.train_ann!r},
    data_prefix=dict(img={args.train_prefix!r})))
val_dataloader = dict(dataset=dict(
    data_root=data_root,
    ann_file={args.val_ann!r},
    data_prefix=dict(img={args.val_prefix!r})))
test_dataloader = val_dataloader
'''
    output.write_text(config_text)
    print(f'Wrote {output}')


if __name__ == '__main__':
    main()
